---
- name: Install Apache Web Server
  hosts: all
  become: yes
  tasks:
  - name: Detect distro family 
    debug: var=ansible_os_family
  - block: 
    - name: Install Apache Web server for Debian 
      apt: name=apache2 state=latest update_cache=yes cache_valid_time=3600
    - name: Apache autostart enable for Debian
      service: name=apache2 state=started enabled=yes
    - name: Install packages list for Debian
      apt: name="{{ item }}" state=latest update_cache=yes cache_valid_time=3600
      loop:
      - nmap
      - wget
      - tree
      - traceroute
      - nload
      - lsof
      - uptimed
    when: ansible_os_family == "Debian"
  - block:
    - name: Install Apache Web server for RHL
      yum: name=httpd state=latest 
    - name: Apache autostart enable for RHL
      service: name=httpd state=started enabled=yes
    - name: Install packages list for RHL
      yum: name="{{ item }}" state=latest 
      loop:
      - nmap
      - wget
      - tree
      - traceroute
      - nload
      - lsof
      - uptimed
    when: ansible_os_family == "RedHat"
  - name: Generate new index.html 
    template: src=index.j2 dest=/var/www/html/index.html mode=0555
    notify: 
    - Restart Apache RHL
    - Restart Apache Ubuntu
  handlers:
    - name: Restart Apache RHL
      service: name=httpd state=restarted
      when: ansible_os_family == "RedHat"
    - name: Restart Apache Ubuntu
      service: name=apache2 state=restarted
      when: ansible_os_family == "Debian"
